# Usar imagen oficial de Nginx (servidor web ligero)
FROM nginx:alpine

# Copiar nuestra aplicación Vue al directorio que Nginx utiliza para servir archivos web
COPY index.html /usr/share/nginx/html/index.html

# Exponer el puerto 80
EXPOSE 80